### ISSUE TITLE
grunt e2e-test error, relies on Windows??

### ISSUE THREAD

**Issue by EMCP** [mknabe/angular-testing-starter#3]
performed the following

`git clone <project_name>`

`sudo npm install`

`grunt e2e-test`

Output : 

```
$ grunt e2e-test
Running "connect:test" (connect) task
Started connect web server on 127.0.0.1:9000.

Running "protractor:continuous" (protractor) task
~angular-testing-starter/node_modules/protractor/lib/driverProviders/local.dp.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at ~angular-testing-starter/node_modules/protractor/selenium/chromedriver.exe
    at LocalDriverProvider.addDefaultBinaryLocs_ (~angular-testing-starter/node_modules/protractor/lib/driverProviders/local.dp.js:42:15)
    at LocalDriverProvider.setupEnv (~angular-testing-starter/node_modules/protractor/lib/driverProviders/local.dp.js:59:8)
    at Runner.run (~angular-testing-starter/node_modules/protractor/lib/runner.js:378:31)
    at Object.init (~angular-testing-starter/node_modules/protractor/lib/launcher.js:130:12)
    at Object.<anonymous> (~angular-testing-starter/node_modules/protractor/lib/cli.js:118:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
>> 
>> Test failed but keep the grunt process alive.

Running "watch:protractor" (watch) task
Waiting...

```

**Comment by mknabe** [comment]
Can you pull latest and try again? The issue seems to be fixed by @Wolfium's pull request

**Comment by EMCP** [comment]
Performed a `git pull`, erased `node_modules`, and tried again.. same error.

Also for reference :  

```
$webdriver-manager update
selenium standalone is up to date.
chromedriver is up to date.
```

**Comment by EMCP** [comment]
Update :

 Seems I need to perform a local update via the following command

`./node_modules/protractor/bin/webdriver-manager update`

Any idea how to let this project reference to my system / global install?

Edit: 

  That hasn't fixed it.. still not able to execute the test

**Comment by EMCP** [comment]
starting to look into it here https://github.com/teerapap/grunt-protractor-runner/issues/45

**Comment by EMCP** [comment]
it's FIXED

`./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update`

What a mess!
